-- Desactiva constraints para poder borrar en cualquier orden
SET REFERENTIAL_INTEGRITY FALSE;

DELETE FROM LINEAS_PEDIDO;
DELETE FROM PEDIDOS;
DELETE FROM CARRITO_ITEMS;
DELETE FROM CARRITOS;
DELETE FROM MOVIMIENTOS_STOCK;
DELETE FROM PRODUCTOS;
DELETE FROM SUBCATEGORIAS;
DELETE FROM CATEGORIAS;
DELETE FROM USUARIOS;

-- Reactiva constraints
SET REFERENTIAL_INTEGRITY TRUE;
